name: darp
description: Uma lib com funções inspiradas do python.
version: 1.0.0
repository: https://github.com/Jotapehh/Darp.git

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
